Feature: add support for an http logger
KBIbiopharma/app_common pull request #51
Opened 2020-09-11 14:16 UTC by jonathanrocher

2020-09-14 16:46 UTC, chamshop requested changes
Several comments, lots of them more questions than anything. I did get a test failure, though:
```
======================================================================
ERROR: test_initialize_with_filelogging (app_common.std_lib.tests.test_logging_utils.TestLoggingInitialization)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\jchambless\source\app_common\app_common\std_lib\tests\test_logging_utils.py", line 84, in test_initialize_with_filelogging
    os.remove(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'test.log'

----------------------------------------------------------------------
```

2020-09-14 16:46 UTC, chamshop commented on app_common/std_lib/logging_utils.py
> +        dt_fmt = "%Y/%m/%d %H:%M:%S"
I am unsure about forcing the use of a certain format in `initialize_logging` and then allowing something different to be used in the function that it is calling. Perhaps it should be an option in `initialize_logging` as well?

2020-09-14 16:46 UTC, chamshop commented on app_common/std_lib/logging_utils.py
> +              "remote handler. Removed the remote handler. Error was '{}'."
Let's use the `f` string here.

2020-09-14 16:46 UTC, chamshop commented on app_common/std_lib/remote_logging_handler.py
> +        self.debug = debug
As I understand these HTTP handlers to work, we should not define all these parameters as class variables with their own doc strings, because each use of the handler will be one-time use. Is this correct?

2020-09-14 16:46 UTC, chamshop commented on app_common/std_lib/remote_logging_handler.py
> +    def clean_msg(self, msg):
Could/Should all these functions that are only used within the class be made private?

2020-09-14 17:56 UTC, jonathanrocher commented on app_common/pyface/logging_utils.py
> +    msg = 'Action requested: {}'.format(action_name)
Sure. Done.

2020-09-14 18:01 UTC, jonathanrocher commented on app_common/std_lib/logging_utils.py
> +from .remote_logging_handler import RequestsHTTPHandler
Relative imports are more resilient to moving files around when together. That said, pycharm's refactor supports that better, so yes, I am ok with moving in that direction.

2020-09-14 18:01 UTC, jonathanrocher commented on app_common/std_lib/logging_utils.py
> +from .remote_logging_handler import RequestsHTTPHandler
Done.

2020-09-14 18:03 UTC, jonathanrocher commented on app_common/std_lib/logging_utils.py
> +        http logging keyword arguments, passed to
Thanks. Done.

2020-09-14 18:04 UTC, jonathanrocher commented on app_common/std_lib/logging_utils.py
> +                         handler_klass=RequestsHTTPHandler, **kwargs):
Agreed. Done.

2020-09-14 18:09 UTC, jonathanrocher commented on app_common/std_lib/logging_utils.py
> +    pkg_list : list
Thanks. Removed

2020-09-14 22:17 UTC, jonathanrocher commented on app_common/std_lib/logging_utils.py
> +        end point needs or that should be stored.
Agreed. Changed.

2020-09-14 22:47 UTC, jonathanrocher commented on app_common/std_lib/logging_utils.py
> +        dt_fmt = "%Y/%m/%d %H:%M:%S"
Yes. Done.

2020-09-14 22:49 UTC, jonathanrocher commented on app_common/std_lib/logging_utils.py
> +              "remote handler. Removed the remote handler. Error was '{}'."
Done

2020-09-14 22:52 UTC, jonathanrocher commented on app_common/std_lib/remote_logging_handler.py
> +        self.debug = debug
A handler will be created at each call to `initialize_logging`. Yes, each application and each session will define its own handler and then use it over and over during the session.

2020-09-14 22:54 UTC, jonathanrocher commented on app_common/std_lib/remote_logging_handler.py
> +    def clean_msg(self, msg):
I didn't make them private because I thought end-users might want to subclass and implement the serialization differently.

2020-09-15 01:58 UTC, jonathanrocher commented
Ready for another look @chamshop . Comments addressed. I believe the test is fixed on Windows too. Please confirm manually on this one test as CircleCI is having some issues.

2020-09-15 02:43 UTC, chamshop approved these changes
That earlier test is now passing, but this one fails during the running of the entire test suite:
```
======================================================================
FAIL: test_open_file (app_common.std_lib.tests.test_filepath_utils.TestOpenFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\jchambless\source\app_common\app_common\std_lib\tests\test_filepath_utils.py", line 210, in test_open_file
    open_file(self.fpath)
  File "C:\Users\jchambless\.edm\envs\app_common-develop-pyqt5-py36\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "c:\users\jchambless\source\app_common\app_common\std_lib\tests\test_filepath_utils.py", line 222, in assert_process_created
    self.assertEqual(len(process_list)+1, len(new_process_list))
AssertionError: 300 != 299
```

However, it passes when I just run it individually. So I suppose we are good to go.

2020-09-15 02:43 UTC, chamshop commented on app_common/std_lib/logging_utils.py
> +    if not dt_fmt:
Do we need to check to ensure that this `dt_fmt` actually conforms to a date-time format?

2020-09-15 02:53 UTC, jonathanrocher commented
Thanks for thre re-review. Let's review that other (fragile) test separately. Merging.

2020-09-15 02:53 UTC, jonathanrocher commented on app_common/std_lib/logging_utils.py
> +    if not dt_fmt:
I am gonna leave that as the responsibility of the calling code.

2020-09-15 02:54 UTC, merged